### ISSUE TITLE
Nice work for you! Best wishes~

### ISSUE THREAD

**Issue by Kahsolt** [ZijianFelixWang/DefQed#1]
Just came from the web news and verify to what degree is it true. 😄 
Now, I'm fond to be convinced of your hard work, and wish your steady progressions on the academical roads towards maybe the field of computation science, programming semantics or things alike.

PS: I myself is also a fan of computational models, programming languages, predicative logic and machine learning stuffs, honored to be your friend. 🍭

**Comment by fearlessling321** [comment]
?
